version: '3.1'

services:

  app:
    build:
      context: ./web-service
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - POSTGRES_PASSWORD=example

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: example

    ports:
      - "5432:5432"